---
title: "BT333 T-cells Analysis - Figures Only"
output: html_notebook
---

```{r}
library(devtools)
library(parallel)
library(ggplot2)
library(ggridges)
library(gridExtra)
library(plyr)
library(tidyr)
library(tibble)
library(pheatmap)
library(piano)
library(DelayedArray)
library(monocle3)
library(UpSetR)
library(dplyr)
library(ggrepel)
library(ggpubr)
```

```{r}
### Load useful function from the sci-plex github repository
source("~/Documents/github_repos/sci-plex/bin/cell_cycle.R")
source("~/Documents/github_repos/sci-plex/bin/dispersions_functions.R")
cc.genes = readRDS("~/Documents/github_repos/sci-plex/bin/cc.genes.RDS")
```

```{r}
# Set output directory for figures
outdir <- "/home/user/Documents/Kinase_project/figures/PDN_Tcells"
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)
```

```{r}
# Load in the data
setwd("/home/user/Documents/Kinase_project/20250430_BT333_Tcell_11chems_run2")
cds <- readRDS("/home/user/Documents/Kinase_project/20250430_BT333_Tcell_11chems_run2/11-final-output//CDS_BT333_Tcells_0_cutoff.RDS")
```

```{r}
# Figure: UMIs per cell
ggplot(colData(cds) %>% as.data.frame() %>% arrange(dplyr::desc(n.umi)) %>% dplyr::mutate(rank = row_number()),
       aes(x = log10(rank), y = log10(n.umi))) +
  geom_point() +
  geom_hline(yintercept = log10(500)) +
  monocle3:::monocle_theme_opts()
ggsave(file.path(outdir, "UMIs_per_cell.png"), dpi = 600, width = 5, height = 3)
```

```{r}
# Filter cells
cds <- cds[,colData(cds)$n.umi >= 500]
cds<- cds[,!is.na(colData(cds)$total_hash_umis_per_cell_ID)]

# Figure: Hash UMI density
ggplot(data = as.data.frame(colData(cds))) +
  aes(x = log10(hash_umis)) +
  geom_density(fill = "lightblue", alpha = 0.7, color = "black") +
  geom_vline(xintercept = log10(5), color = "red", size = 0.5) +
  annotate("text", x = log10(5), y = 1, label = "Cutoff = 5", angle = 90, vjust = -0.5) +
  theme_classic() +
  xlab("Log10(Hash UMIs)") +
  ylab("Density")
ggsave(file.path(outdir, "hash_UMI_density_plot.png"), dpi = 600, height = 2, width = 5)
```

```{r}
# Additional filtering
cds<-cds[,colData(cds)$total_hash_umis_per_cell_ID>5]
cds<-cds[,colData(cds)$top_to_second_best_ratio>2]
```

```{r}
# Extract and process metadata
col_data_df <- as.data.frame(colData(cds))
col_data_df <- col_data_df %>%
  separate(oligo, 
           into = c("Experiment", "Drug", "Dose", "Tcell_Treatment", "Replicate", "Well"),
           sep = "_", 
           remove = FALSE)
colData(cds) <- DataFrame(col_data_df)
```

```{r}
# Create combined treatment columns
cell_data <- as.data.frame(colData(cds))
cell_data$drug_dose_treatment <- paste(cell_data$Drug, cell_data$Dose, cell_data$Tcell_Treatment, sep="_")
cell_data$dose_treatment <- paste(cell_data$Dose, cell_data$Tcell_Treatment, sep="_")
colData(cds)$drug_dose_treatment <- cell_data$drug_dose_treatment
colData(cds)$dose_treatment <- cell_data$dose_treatment
colData(cds)$drug_dose_treatment <- factor(colData(cds)$drug_dose_treatment)
```

```{r}
# Remove NA oligos
cds <-cds[,!is.na(colData(cds)$oligo)]
```

```{r}
# Load differential gene expression test results
Tcell_dose_response_diff_test = readRDS("/home/user/Documents/Kinase_project/crispra_final/CRISPRA_Figures/NTC_analysis/DEG_testing/NTC_CRISPR_dose_response_diff_test_replicates.rds")
```

```{r}
# Identify high-value genes for clustering
volcano_data <- Tcell_dose_response_diff_test %>%
  filter(grepl("dose", term))
high_value_points <- volcano_data %>%
  filter(q_value < 0.05 & abs(normalized_effect) > 0.25)
```

```{r}
# Preprocessing and dimensionality reduction
cds <- estimate_size_factors(cds)
cds <- detect_genes(cds)
cds <- estimate_cell_cycle(cds, g1s_markers = cc.genes$s.genes, g2m_markers = cc.genes$g2m.genes)

expressed_genes <- row.names(fData(cds)[Matrix::rowSums(exprs(cds) > 0) > 
                                              dim(cds)[2]*0.05,])

disp_table <- estimateDispersionsForCellDataSet(cds,
                                         min_cells_detected = 100,
                                         removeOutliers = FALSE)

disp_table <-
  dispersionTable(disp_table) %>%
  mutate(excess_disp = (dispersion_empirical - dispersion_fit) / dispersion_fit)

disp_table <- tibble(gene_id = disp_table$gene_id,
                     mean_expression = disp_table$mean_expression, 
                     excess_disp = disp_table$excess_disp)

unsup_clustering_genes =
  disp_table %>%
  dplyr::arrange(desc(excess_disp)) %>%
  dplyr::slice(1:5000) %>%
  ungroup() %>%
  pull(gene_id) %>%
  unique()

library(Matrix)

cds <- preprocess_cds(cds,
                      num_dim = 20,
                      use_genes = high_value_points$id)

cds <- reduce_dimension(cds, 
                        umap.n_neighbors = 20L, 
                        umap.min_dist = 0.1, 
                        max_components = 2,
                        umap.fast_sgd = FALSE,
                        cores = 1)

colData(cds)$UMAP1 <- reducedDims(cds)[["UMAP"]][,1]
colData(cds)$UMAP2 <- reducedDims(cds)[["UMAP"]][,2]
```

```{r}
# Clustering
cds <- cluster_cells(cds, reduction_method = "PCA", resolution = 7e-5, random_seed = 2016L, num_iter = 1)
colData(cds)$PCA_Cluster <- clusters(cds, reduction_method = "PCA")
```

```{r}
# Figure: UMAP by PCA cluster
cluster_colors <- c("1" = "#FFBA49", "2" = "#20A39E", "3" = "#EF5B5B")

plot_cells(cds, color_cells_by = "PCA_Cluster",cell_size = 0.2) +
  scale_color_manual(values = cluster_colors) +
theme_void() +
theme(legend.position = "right",
        legend.key.width = unit(0.2,"line"),
        legend.key.height = unit(0.2,"line"))
ggsave(file.path(outdir, "umap_pca_cluster.png"), dpi = 600, width = 3, height = 1.5)
ggsave(file.path(outdir, "umap_pca_cluster.pdf"), dpi = 600, width = 3, height = 1.5)
ggsave(file.path(outdir, "umap_pca_cluster.svg"), dpi = 600, width = 3, height = 1.5)

# Figure: UMAP by T-cell treatment
dosage_colors <- c('NoT' = '#023047', '0.5T' = '#FFD166')
plot_cells(cds, color_cells_by = "Tcell_Treatment",cell_size = 0.2) +
  scale_color_manual(values = dosage_colors) +
theme_void() +
theme(legend.position = "right",
        legend.key.width = unit(0.2,"line"),
        legend.key.height = unit(0.2,"line"))
ggsave(file.path(outdir, "umap_tcell_treatment.png"), dpi = 600, width = 3, height = 1.5)
ggsave(file.path(outdir, "umap_tcell_treatment.pdf"), dpi = 600, width = 3, height = 1.5)
ggsave(file.path(outdir, "umap_tcell_treatment.svg"), dpi = 600, width = 3, height = 1.5)
```

```{r}
# Figure: T-cell treatment by PCA cluster
ggplot(colData(cds) %>% as.data.frame(),
       aes(x = as.character(PCA_Cluster), fill = Tcell_Treatment)) +
  geom_bar(position = "fill", color = "black", size = 0.25) +
  scale_fill_manual(
    values = dosage_colors,
    name = "T-cell\nto GBM ratio"
  ) +
  monocle3:::monocle_theme_opts() +
  theme(
    text = element_text(size = 6),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.key.width = unit(0.4, "line"),
    legend.key.height = unit(0.4, "line")
  ) +
  xlab("PCA cluster")
ggsave(file.path(outdir, "Tcell_Treatment_and_PCA_Cluster.png"), dpi = 600, width = 1.7, height = 1.1)
ggsave(file.path(outdir, "Tcell_Treatment_and_PCA_Cluster.pdf"), dpi = 600, width = 1.7, height = 1.1)
ggsave(file.path(outdir, "Tcell_Treatment_and_PCA_Cluster.svg"), dpi = 600, width = 1.7, height = 1.1)
```

```{r}
# Figure: Chemical proportion per cluster
library(ggplot2)
library(dplyr, warn.conflicts = FALSE)

if("package:plyr" %in% search()) {
  detach("package:plyr", unload = TRUE)
}

cell_data <- as.data.frame(colData(cds))
freq_table <- table(cell_data$Drug, cell_data$PCA_Cluster)
prop_table <- prop.table(freq_table, margin = 1)
prop_df <- as.data.frame(prop_table)
colnames(prop_df) <- c("Drug", "PCA_Cluster", "Proportion")
cluster2_props <- prop_df[prop_df$PCA_Cluster == "2", ]
cluster2_props <- cluster2_props[order(cluster2_props$Proportion, decreasing = TRUE), ]
drug_order <- as.character(cluster2_props$Drug)
cell_data$Drug_ordered <- factor(as.character(cell_data$Drug), levels = drug_order)

ggplot(cell_data, aes(x = Drug_ordered, fill = PCA_Cluster)) +
  geom_bar(position = "fill", color = "black", size = 0.25) +
  scale_fill_manual(values = cluster_colors) +
  monocle3:::monocle_theme_opts() +
  theme(text = element_text(size = 6),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.key.width = unit(0.4,"line"),
        legend.key.height = unit(0.4,"line")) +
  guides(fill = guide_legend(override.aes = list(size=3))) +
  xlab("") +
  ylab("Proportion") +
  labs(title = "",
       fill = "PCA Cluster")
ggsave(file.path(outdir, "Chemcial_proportionpercluster.png"), dpi = 600, width = 3, height = 1.5)
ggsave(file.path(outdir, "Chemcial_proportionpercluster.pdf"), dpi = 600, width = 3, height = 1.5)
ggsave(file.path(outdir, "Chemcial_proportionpercluster.svg"), dpi = 600, width = 3, height = 1.5)
```


```{r}
# Figure: Proliferation comparison per drug
plot_data <- as.data.frame(colData(cds))

for (drug in unique(plot_data$Drug)) {
  
  current_drug_data <- plot_data[plot_data$Drug == drug, ]
  current_drug_data$dose <- sub("(.*)_(.*)", "\\1", current_drug_data$dose_treatment)
  current_drug_data$Tcell_Treatment <- sub("(.*)_(.*)", "\\2", current_drug_data$dose_treatment)
  
  p <- ggplot(current_drug_data, 
         aes(x = factor(dose, levels = c('0.01', '0.1', '1', '10')), 
             y = proliferation_index, 
             color = factor(Tcell_Treatment, levels = c('0.5T', 'NoT')),
             group = Tcell_Treatment)) +
    stat_summary(fun = mean, geom = "line", size = 0.8) +
    stat_summary(fun = mean, geom = "point", size = 2) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
    monocle3:::monocle_theme_opts() +
    scale_color_manual("T-cell treatment", 
                       values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    scale_fill_manual("T-cell treatment", 
                      values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    theme(text = element_text(size = 8),
          legend.position = "right",
          legend.title = element_text(size = 7),
          legend.text = element_text(size = 7),
          legend.key.size = unit(0.4, "cm"),
          axis.text.x = element_text(size = 8)) +
    xlab("Dose (µM)") +
    ylab("Proliferation index") +
    ggtitle(paste0(drug))
  
  ggsave(file.path(outdir, paste0(drug, "_proliferation_comparison.png")), 
         plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_proliferation_comparison.svg")), 
         plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_proliferation_comparison.pdf")), 
         plot = p, dpi = 600, height = 1.5, width = 3)
}
```


```{r}
# Calculate gene signature scores
APM_MHC_CI_genes <- c("PSMB5","PSMB6","PSMB7","PSMB8","PSMB9","PSMB10","TAP1","TAP2","ERAP1","ERAP2","CANX","CALR","PDIA3","TAPBP","B2M","HLA-A","HLA-B","HLA-C")
APM_MHC_CII_genes <- c("CIITA", "HLA-DRA", "HLA-DRB1", "HLA-DRB5", "HLA-DRB6", "HLA-DQA1", "HLA-DQB1", "HLA-DPA1", "HLA-DMA", "HLA-DMB", "HLA-DOA")
MKI67_genes <- c('MKI67')

calculate_aggregate_expression_score <- function(cds, signature_genes, from_id = FALSE){
  if(from_id == TRUE){
    cds_subset = cds[rowData(cds)$id %in% signature_genes,]
  }
  else(cds_subset = cds[rowData(cds)$gene_short_name %in% signature_genes,])
  aggregate_signature_expression = exprs(cds_subset)
  aggregate_signature_expression = t(t(aggregate_signature_expression) / pData(cds_subset)$Size_Factor)
  aggregate_signature_expression = Matrix::colSums(aggregate_signature_expression)
  signature_score = log(aggregate_signature_expression+1)
  return(signature_score)
}

colData(cds)$APM_MHC_CI_score <- calculate_aggregate_expression_score(cds, signature_genes = APM_MHC_CI_genes)
colData(cds)$APM_MHC_CII_score <- calculate_aggregate_expression_score(cds, signature_genes = APM_MHC_CII_genes)
colData(cds)$MKI67 <- calculate_aggregate_expression_score(cds, signature_genes = MKI67_genes)
```

```{r}
# Figure: MKI67 comparison per drug
plot_data <- as.data.frame(colData(cds))
dmso_data <- plot_data[plot_data$Drug == "DMSO", ]
dmso_data$dose <- sub("(.*)_(.*)", "\\1", dmso_data$dose_treatment)
dmso_data$Tcell_Treatment <- sub("(.*)_(.*)", "\\2", dmso_data$dose_treatment)
dmso_means <- aggregate(MKI67 ~ Tcell_Treatment, data = dmso_data, FUN = mean)
drug_data <- plot_data[plot_data$Drug != "DMSO", ]

for (drug in unique(drug_data$Drug)) {
  current_drug_data <- drug_data[drug_data$Drug == drug, ]
  current_drug_data$dose <- sub("(.*)_(.*)", "\\1", current_drug_data$dose_treatment)
  current_drug_data$Tcell_Treatment <- sub("(.*)_(.*)", "\\2", current_drug_data$dose_treatment)
  
  p <- ggplot(current_drug_data, 
         aes(x = factor(dose, levels = c('0.01', '0.1', '1', '10')), 
             y = MKI67, 
             color = factor(Tcell_Treatment, levels = c('0.5T', 'NoT')),
             group = Tcell_Treatment)) +
    geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "0.5T", ],
               aes(yintercept = MKI67, linetype = "DMSO 0.5T"), 
               color = "#FFD166", alpha = 0.7) +
    geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "NoT", ],
               aes(yintercept = MKI67, linetype = "DMSO NoT"), 
               color = "#023047", alpha = 0.7) +
    stat_summary(fun = mean, geom = "line", size = 0.8) +
    stat_summary(fun = mean, geom = "point", size = 2) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
    monocle3:::monocle_theme_opts() +
    scale_color_manual("T-cell treatment", 
                       values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    scale_fill_manual("T-cell treatment", 
                      values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    scale_linetype_manual("DMSO control", 
                          values = c("DMSO 0.5T" = "dashed", "DMSO NoT" = "dashed")) +
    theme(text = element_text(size = 8),
          legend.position = "right",
          legend.title = element_text(size = 7),
          legend.text = element_text(size = 7),
          legend.key.size = unit(0.4, "cm"),
          axis.text.x = element_text(size = 8)) +
    xlab("Dose (µM)") +
    ylab("MKI67") +
    ggtitle(paste0(drug))
  
  ggsave(file.path(outdir, paste0(drug, "_MKI67_comparison.png")), plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_MKI67_comparison.pdf")), plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_MKI67_comparison.svg")), plot = p, dpi = 600, height = 1.5, width = 3)
}
```

```{r}
# Figure: MKI67 by T-cell treatment
plot_data <- as.data.frame(colData(cds))
  
ggplot(plot_data, 
       aes(x = factor(Tcell_Treatment, levels = c('NoT', '0.5T')), 
           y = MKI67, 
           fill = factor(Tcell_Treatment, 
                        levels = c('NoT', '0.5T')))) +
  geom_violin(color = "black", size = 0.1) +
  stat_summary(fun = mean, geom = "point", size = 0.1) +
  monocle3:::monocle_theme_opts() +
  scale_fill_manual("T-cell treatment",
                    values = c('NoT' = "#023047",
                      '0.5T' = "#FFD166")) +
  theme(text = element_text(size = 6),
        legend.position = "none",
        axis.text.x = element_text(size = 4, angle = 45, hjust = 1)) +
  xlab("T-cell treatment") +
  ylab("Proliferation index") +
  ggpubr::stat_compare_means(size = 1.5, 
                            method = "t.test",
                            label = "p.signif", 
                            label.x = 1.5)
ggsave(file.path(outdir, "MKI67_Tcell_treatment.png"), dpi = 600, height = 1.5, width = 1)
```

```{r}
# Figure: MHCI by T-cell treatment
plot_data <- as.data.frame(colData(cds))
  
ggplot(plot_data, 
       aes(x = factor(Tcell_Treatment, levels = c('NoT', '0.5T')), 
           y = APM_MHC_CI_score, 
           fill = factor(Tcell_Treatment, 
                        levels = c('NoT', '0.5T')))) +
  geom_violin(color = "black", size = 0.1) +
  stat_summary(fun = mean, geom = "point", size = 0.1) +
  monocle3:::monocle_theme_opts() +
  scale_fill_manual("T-cell treatment",
                    values = c('NoT' = "#023047",
                      '0.5T' = "#FFD166")) +
  theme(text = element_text(size = 6),
        legend.position = "none",
        axis.text.x = element_text(size = 4, angle = 45, hjust = 1)) +
  xlab("T-cell treatment") +
  ylab("MHCI Score") +
  ggpubr::stat_compare_means(size = 1.5, 
                            method = "t.test",
                            label = "p.signif", 
                            label.x = 1.5)
ggsave(file.path(outdir, "MHCI_Tcell_treatment.png"), dpi = 600, height = 1.5, width = 1)
```

```{r}
# Figure: MHC1 comparison per drug
plot_data <- as.data.frame(colData(cds))
dmso_data <- plot_data[plot_data$Drug == "DMSO", ]
dmso_data$dose <- sub("(.*)_(.*)", "\\1", dmso_data$dose_treatment)
dmso_data$Tcell_Treatment <- sub("(.*)_(.*)", "\\2", dmso_data$dose_treatment)
dmso_means <- aggregate(APM_MHC_CI_score ~ Tcell_Treatment, data = dmso_data, FUN = mean)
drug_data <- plot_data[plot_data$Drug != "DMSO", ]

for (drug in unique(drug_data$Drug)) {
  current_drug_data <- drug_data[drug_data$Drug == drug, ]
  current_drug_data$dose <- sub("(.*)_(.*)", "\\1", current_drug_data$dose_treatment)
  current_drug_data$Tcell_Treatment <- sub("(.*)_(.*)", "\\2", current_drug_data$dose_treatment)
  
  p <- ggplot(current_drug_data, 
         aes(x = factor(dose, levels = c('0.01', '0.1', '1', '10')), 
             y = APM_MHC_CI_score, 
             color = factor(Tcell_Treatment, levels = c('0.5T', 'NoT')),
             group = Tcell_Treatment)) +
    geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "0.5T", ],
               aes(yintercept = APM_MHC_CI_score, linetype = "DMSO 0.5T"), 
               color = "#FFD166",
               alpha = 0.7) +
    geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "NoT", ],
               aes(yintercept = APM_MHC_CI_score, linetype = "DMSO NoT"), 
               color = "#023047", 
               alpha = 0.7) +
    stat_summary(fun = mean, geom = "line", size = 0.8) +
    stat_summary(fun = mean, geom = "point", size = 2) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
    monocle3:::monocle_theme_opts() +
    scale_color_manual("T-cell treatment", 
                       values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    scale_fill_manual("T-cell treatment", 
                      values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    scale_linetype_manual("DMSO control", 
                          values = c("DMSO 0.5T" = "dashed", "DMSO NoT" = "dashed")) +
    theme(text = element_text(size = 8),
          legend.position = "right",
          legend.title = element_text(size = 7),
          legend.text = element_text(size = 7),
          legend.key.size = unit(0.4, "cm"),
          axis.text.x = element_text(size = 8)) +
    xlab("Dose (µM)") +
    ylab("MHCI Score") +
    ggtitle(paste0(drug))
  
  ggsave(file.path(outdir, paste0(drug, "_MHC1_comparison.png")), plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_MHC1_comparison.pdf")), plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_MHC1_comparison.svg")), plot = p, dpi = 600, height = 1.5, width = 3)
}
```

```{r}
# Figure: MHCII by T-cell treatment
plot_data <- as.data.frame(colData(cds))
  
ggplot(plot_data, 
       aes(x = factor(Tcell_Treatment, levels = c('NoT', '0.5T')), 
           y = APM_MHC_CII_score, 
           fill = factor(Tcell_Treatment, 
                        levels = c('NoT', '0.5T')))) +
  geom_violin(color = "black", size = 0.1) +
  stat_summary(fun = mean, geom = "point", size = 0.1) +
  monocle3:::monocle_theme_opts() +
  scale_fill_manual("T-cell treatment",
                    values = c('NoT' = "#023047",
                      '0.5T' = "#FFD166")) +
  theme(text = element_text(size = 6),
        legend.position = "none",
        axis.text.x = element_text(size = 4, angle = 45, hjust = 1)) +
  xlab("T-cell treatment") +
  ylab("MHCII Score") +
  ggpubr::stat_compare_means(size = 1.5, 
                            method = "t.test",
                            label = "p.signif", 
                            label.x = 1.5)
ggsave(file.path(outdir, "MHCII_Tcell_treatment.png"), dpi = 600, height = 1.5, width = 1)
```

```{r}
# Figure: MHCII comparison per drug
plot_data <- as.data.frame(colData(cds))
dmso_data <- plot_data[plot_data$Drug == "DMSO", ]
dmso_means <- aggregate(APM_MHC_CII_score ~ Tcell_Treatment, data = dmso_data, FUN = mean)
drug_data <- plot_data[plot_data$Drug != "DMSO", ]

for (drug in unique(drug_data$Drug)) {
  current_drug_data <- drug_data[drug_data$Drug == drug, ]
  current_drug_data$dose <- sub("(.*)_(.*)", "\\1", current_drug_data$dose_treatment)
  current_drug_data$Tcell_Treatment <- sub("(.*)_(.*)", "\\2", current_drug_data$dose_treatment)
  
  p <- ggplot(current_drug_data, 
         aes(x = factor(dose, levels = c('0.01', '0.1', '1', '10')), 
             y = APM_MHC_CII_score, 
             color = factor(Tcell_Treatment, levels = c('0.5T', 'NoT')),
             group = Tcell_Treatment)) +
    geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "0.5T", ],
               aes(yintercept = APM_MHC_CII_score, linetype = "DMSO 0.5T"), 
               color = "#FFD166",
               alpha = 0.7) +
    geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "NoT", ],
               aes(yintercept = APM_MHC_CII_score, linetype = "DMSO NoT"), 
               color = "#023047", 
               alpha = 0.7) +
    stat_summary(fun = mean, geom = "line", size = 0.8) +
    stat_summary(fun = mean, geom = "point", size = 2) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
    monocle3:::monocle_theme_opts() +
    scale_color_manual("T-cell treatment", 
                       values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    scale_fill_manual("T-cell treatment", 
                      values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    scale_linetype_manual("DMSO control", 
                          values = c("DMSO 0.5T" = "dashed", "DMSO NoT" = "dashed")) +
    theme(text = element_text(size = 8),
          legend.position = "right",
          legend.title = element_text(size = 7),
          legend.text = element_text(size = 7),
          legend.key.size = unit(0.4, "cm"),
          axis.text.x = element_text(size = 8)) +
    xlab("Dose (µM)") +
    ylab("MHCII Score") +
    ggtitle(paste0(drug))
  
  ggsave(file.path(outdir, paste0(drug, "_MHCII_comparison.png")), plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_MHCII_comparison.pdf")), plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_MHCII_comparison.svg")), plot = p, dpi = 600, height = 1.5, width = 3)
}
```

```{r}
# Figure: Gene expression violins for specific genes
treatment_order <- c("NoT",'0.5T')
cds$Tcell_Treatment <- factor(cds$Tcell_Treatment, levels = treatment_order)

for(gene in c("MKI67", "SOD2", "CD274", "IDO1", "CSF3")) {
  plot_genes_violin(cds[rowData(cds)$gene_short_name == gene,], 
                    group_cells_by = "Tcell_Treatment", 
                    pseudocount = 1) +
        theme(legend.position = "right",
              axis.text = element_text(size = 6),
              axis.text.x = element_text(angle = 45, hjust = 1),
              legend.key.width = unit(0.2, "line"),
              legend.key.height = unit(0.2, "line"))+
    scale_fill_manual("T-cell treatment",
                      values = c('NoT' = "#023047",
                        '0.5T' = "#FFD166")) +
    ggpubr::stat_compare_means(size = 1.5, 
                               method = "t.test",
                               label = "p.signif", 
                               label.x = 1.5)
  ggsave(file.path(outdir, paste0(gene, "_Tcell_treatment_violin.png")), dpi = 600, height = 2, width = 1.5)
}
```

```{r}
# Figure: Gene expression comparison per drug for SOD2, CD274, IDO1
for(gene_to_plot in c("SOD2", "CD274", "IDO1")) {
  gene_idx <- which(rowData(cds)$gene_short_name == gene_to_plot)
  expression_data <- log10(exprs(cds)[gene_idx, ] + 1)
  
  plot_data <- as.data.frame(colData(cds))
  plot_data$gene_expression <- expression_data[match(rownames(plot_data), names(expression_data))]
  
  dmso_data <- plot_data[plot_data$Drug == "DMSO", ]
  dmso_means <- aggregate(gene_expression ~ Tcell_Treatment, data = dmso_data, FUN = mean)
  drug_data <- plot_data[plot_data$Drug != "DMSO", ]
  
  for (drug in unique(drug_data$Drug)) {
    current_drug_data <- drug_data[drug_data$Drug == drug, ]
    current_drug_data$dose <- sub("(.*)_(.*)", "\\1", current_drug_data$dose_treatment)
    current_drug_data$Tcell_Treatment <- sub("(.*)_(.*)", "\\2", current_drug_data$dose_treatment)
    
    p <- ggplot(current_drug_data, 
           aes(x = factor(dose, levels = c('0.01', '0.1', '1', '10')), 
               y = gene_expression,
               color = factor(Tcell_Treatment, levels = c('0.5T', 'NoT')),
               group = Tcell_Treatment)) +
      geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "0.5T", ],
                 aes(yintercept = gene_expression, linetype = "DMSO 0.5T"), 
                 color = "#FFD166",
                 alpha = 0.7) +
      geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "NoT", ],
                 aes(yintercept = gene_expression, linetype = "DMSO NoT"), 
                 color = "#023047", 
                 alpha = 0.7) +
      stat_summary(fun = mean, geom = "line", size = 0.8) +
      stat_summary(fun = mean, geom = "point", size = 2) +
      stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
      monocle3:::monocle_theme_opts() +
      scale_color_manual("T-cell treatment", 
                         values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
      scale_fill_manual("T-cell treatment", 
                        values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
      scale_linetype_manual("DMSO control", 
                            values = c("DMSO 0.5T" = "dashed", "DMSO NoT" = "dashed")) +
      theme(text = element_text(size = 8),
            legend.position = "right",
            legend.title = element_text(size = 7),
            legend.text = element_text(size = 7),
            legend.key.size = unit(0.4, "cm"),
            axis.text.x = element_text(size = 8)) +
      xlab("Dose (µM)") +
      ylab(paste0(gene_to_plot, " Expression (log10)")) +
      ggtitle(paste0(drug))
    
    ggsave(file.path(outdir, paste0(drug, "_", gene_to_plot, "_expression_comparison.png")), 
           plot = p, dpi = 600, height = 1.5, width = 3)
    ggsave(file.path(outdir, paste0(drug, "_", gene_to_plot, "_expression_comparison.pdf")), 
           plot = p, dpi = 600, height = 1.5, width = 3)
    ggsave(file.path(outdir, paste0(drug, "_", gene_to_plot, "_expression_comparison.svg")), 
           plot = p, dpi = 600, height = 1.5, width = 3)
  }
}
```

```{r}
# Calculate T-cell dose response score
volcano_data <- Tcell_dose_response_diff_test %>%
  filter(grepl("dose", term))
high_value_points <- volcano_data %>%
  filter(q_value < 0.001 & abs(normalized_effect) > 1)
Tcell_dose_genes <- high_value_points$gene_short_name

colData(cds)$Tcell_dose_response_score <- calculate_aggregate_expression_score(cds, signature_genes = Tcell_dose_genes)
```

```{r}
# Figure: T-cell dose response score comparison per drug
plot_data <- as.data.frame(colData(cds))
dmso_data <- plot_data[plot_data$Drug == "DMSO", ]
dmso_means <- aggregate(Tcell_dose_response_score ~ Tcell_Treatment, data = dmso_data, FUN = mean)
drug_data <- plot_data[plot_data$Drug != "DMSO", ]

for (drug in unique(drug_data$Drug)) {
  current_drug_data <- drug_data[drug_data$Drug == drug, ]
  current_drug_data$dose <- sub("(.*)_(.*)", "\\1", current_drug_data$dose_treatment)
  current_drug_data$Tcell_Treatment <- sub("(.*)_(.*)", "\\2", current_drug_data$dose_treatment)
  
  p <- ggplot(current_drug_data, 
         aes(x = factor(dose, levels = c('0.01', '0.1', '1', '10')), 
             y = Tcell_dose_response_score, 
             color = factor(Tcell_Treatment, levels = c('0.5T', 'NoT')),
             group = Tcell_Treatment)) +
    geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "0.5T", ],
               aes(yintercept = Tcell_dose_response_score, linetype = "DMSO 0.5T"), 
               color = "#FFD166",
               alpha = 0.7) +
    geom_hline(data = dmso_means[dmso_means$Tcell_Treatment == "NoT", ],
               aes(yintercept = Tcell_dose_response_score, linetype = "DMSO NoT"), 
               color = "#023047", 
               alpha = 0.7) +
    stat_summary(fun = mean, geom = "line", size = 0.8) +
    stat_summary(fun = mean, geom = "point", size = 2) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
    monocle3:::monocle_theme_opts() +
    scale_color_manual("T-cell treatment", 
                       values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    scale_fill_manual("T-cell treatment", 
                      values = c('0.5T' = "#FFD166", 'NoT' = "#023047")) +
    scale_linetype_manual("DMSO control", 
                          values = c("DMSO 0.5T" = "dashed", "DMSO NoT" = "dashed")) +
    theme(text = element_text(size = 8),
          legend.position = "right",
          legend.title = element_text(size = 7),
          legend.text = element_text(size = 7),
          legend.key.size = unit(0.4, "cm"),
          axis.text.x = element_text(size = 8)) +
    xlab("Dose (µM)") +
    ylab("Tcell_dose_response_score") +
    ggtitle(paste0(drug))
  
  ggsave(file.path(outdir, paste0(drug, "_Tcell_dose_response_score_comparison.png")), 
         plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_Tcell_dose_response_score_comparison.pdf")), 
         plot = p, dpi = 600, height = 1.5, width = 3)
  ggsave(file.path(outdir, paste0(drug, "_Tcell_dose_response_score_comparison.svg")), 
         plot = p, dpi = 600, height = 1.5, width = 3)
}
```

```{r}
# Figure: T-cell dose response score by treatment
plot_data <- as.data.frame(colData(cds))
ggplot(plot_data, 
       aes(x = factor(Tcell_Treatment, levels = c('NoT', '0.5T')), 
           y = Tcell_dose_response_score, 
           fill = factor(Tcell_Treatment, 
                        levels = c('NoT', '0.5T')))) +
  geom_violin(color = "black", size = 0.1) +
  stat_summary(fun = mean, geom = "point", size = 0.1) +
  monocle3:::monocle_theme_opts() +
  scale_fill_manual("T-cell treatment",
                    values = c('NoT' = "#023047",
                      '0.5T' = "#FFD166")) +
  theme(text = element_text(size = 6),
        legend.position = "none",
        axis.text.x = element_text(size = 4, angle = 45, hjust = 1)) +
  xlab("T-cell treatment") +
  ylab("Tcell_dose_response_score") +
  ggpubr::stat_compare_means(size = 1.5, 
                            method = "t.test",
                            label = "p.signif", 
                            label.x = 1.5)
ggsave(file.path(outdir, "Tcell_dose_response_score_Tcell_treatment.png"), dpi = 600, height = 1.5, width = 1)
```

```{r}
# Save processed CDS
saveRDS(cds, "preprocessed_cds_with_gene_sig.rds")
```
```{r}

```